version: '3'
services:
  web:
    # command: odoo -d test-19 -u similar_products --dev xml --test-enable --log-level=test --stop-after-init
    # command: odoo -d test-19 -i base,web,similar_products --dev xml
    command: odoo -d test-19 -u similar_products --dev xml
    # command: odoo -d test-19 -i base,web --dev xml
    image: odoo:19.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      # - ./config:/etc/odoo
      - ./:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:16
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./data/test-19:/var/lib/postgresql/data
