version: '3'
services:
  web:
    command: odoo -d test -u similar_products,sales_order_name_unique --dev xml --test-enable
    # command: odoo -d test -i base,web,similar_products,sales_order_name_unique --dev xml
    image: odoo:15.0
    depends_on:
      - db
    ports:
      - "8001:8069"
    volumes:
    #   - ./config:/etc/odoo
      - ./:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:10
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    # volumes:
    #   - ../data/odoo-db-data-base:/var/lib/postgresql/data
